name: CI
on:
  push:
    branches: [main]
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    defaults:
      run:
        shell: bash
    runs-on: ["ubuntu-latest"]
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Poetry setup
        uses: Gr1N/setup-poetry@v9
      - run: poetry install --with=test
      - name: Run the tests
        run: pytest
