name: Docs
on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v9
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - run: poetry config virtualenvs.in-project true
        name: venv in project
      - run: poetry install --with=docs
        name: Poetry install
      - run: mkdocs build
        name: MKdocs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
